# Spring properties
spring:
  application:
    name: auth-service


management:
  security:
    basic: false


# Mongo properties
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local





# HTTP Server
server:
  port: 4444



# Auth JWT
jwt:
  header: Authorization
  secret: quebic_secret
  expiration: 172800 #seconds
  route:
    authentication:
      path: auth
      refresh: refresh




